"""Adiciona coluna tipo em ContaRecorrente

Revision ID: 2634f27fbbe6
Revises: afbeda50b4c3
Create Date: 2025-11-21 03:32:09.757260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2634f27fbbe6'
down_revision = 'afbeda50b4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_recorrente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_recorrente', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
